Final NextTrip/NextTrip/NextTrip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('loginpage.urls')),
    path('nextbus/',include('nextbus.urls')),
    path('buytickets/',include('buytickets.urls')),
    #  path('buytickets/', include('buytickets.urls',namespace='buytickets')),
    path('reviews/',include('reviews.urls')),
    # path('payment/',include('payment.urls')),


     

]

Final NextTrip/NextTrip/buytickets/urls.py
from django.urls import path
from . import views 
from .views import ticket_details

app_name = 'buytickets'

urlpatterns = [
    path('buy_ticket/', views.buy_ticket, name='buy_ticket'),
    path('paypalbuy_ticket/', views.paypalbuy_ticket, name='paypalbuy_ticket'),

      path('paypalbuy_ticket/', views.paypalbuy_ticket, name='paypalbuy_ticket'),

    path('payment_success/', views.payment_success, name='payment_success'),
    # path('verify_ticket/<int:ticket_id>/', views.verify_ticket, name='verify_ticket'),
    # path('manager/', views.manager_view, name='manager_view'),
    # Other URL patterns
    path('ticket-details/', ticket_details, name='ticket_details'),
]

Final NextTrip/NextTrip/nextbus/urls.py
from django.urls import path
from nextbus import views

urlpatterns = [
    path('search/', views.search_buses, name='search_buses'),
    path('bus/<str:bus_name>/', views.bus_reviews, name='bus_reviews'),
    
    #  path('get_stations/', views.get_stations, name='get_stations'),


    # path('get_station_suggestions/', views.get_station_suggestions, name='get_station_suggestions'),

    


]

Final NextTrip/NextTrip/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('review/', views.review_form, name='review_form'),
    path('all/', views.all_reviews, name='all_reviews'),
    path('bus/<str:bus_name>/', views.bus_reviews, name='bus_reviews'),

    path('submit_query/', views.submit_query, name='submit_query'),
    
    # URL pattern for submitting the query form data
    # path('submit_query/', views.submit_query, name='submit_query'),
]

Final NextTrip/NextTrip/buytickets/models.py
from django.db import models
from django.contrib.auth.models import User
from nextbus.models import Station, Bus

class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    origin = models.ForeignKey(Station, on_delete=models.CASCADE, related_name='origin_tickets')
    destination = models.ForeignKey(Station, on_delete=models.CASCADE, related_name='destination_tickets')
    date = models.DateField()
    time = models.TimeField()
    cost = models.FloatField()
    ticket_number = models.CharField(max_length=10, unique=True)
    is_verified = models.BooleanField(default=False)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)  # ForeignKey to Bus model

Final NextTrip/NextTrip/buytickets/forms.py
# # forms.py

# from django import forms
# from nextbus.models import Bus
# from .models import Ticket

# class TicketForm(forms.ModelForm):
#     bus = forms.ModelChoiceField(queryset=Bus.objects.all(), label='Bus')

#     class Meta:
#         model = Ticket
#         fields = ['origin', 'destination', 'date', 'time', 'cost', 'bus']

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['date'].widget.attrs['class'] = 'datepicker'  # Add CSS class for datepicker
#         self.fields['time'].widget.attrs['class'] = 'timepicker'  # Add CSS class for timepicker























# ##################

from django import forms
from .models import Ticket
from django.utils import timezone

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['origin','destination', 'date', 'time', 'cost','bus']

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)
        self.initial['date'] = timezone.now().date()
        self.initial['time'] = timezone.now().strftime('%H:%M')


################################################

Final NextTrip/NextTrip/buytickets/views.py
# from django.shortcuts import render, redirect
# from .forms import TicketForm
# from .models import Ticket
# from django.contrib.auth.decorators import login_required
# from nextbus.models import Station
# import uuid

# @login_required
# def buy_ticket(request):
#     origin_stations = Station.objects.all()
#     destination_stations = Station.objects.all()

#     if request.method == 'POST':
#         form = TicketForm(request.POST)
#         if form.is_valid():
#             ticket = form.save(commit=False)
#             ticket.user = request.user
#             ticket.ticket_number = uuid.uuid4().hex[:10]
#             ticket.save()
#             return redirect('buytickets:payment_success')

#     else:
#         form = TicketForm()
#     return render(request, 'buytickets/buy_ticket.html', {'form': form, 'user_name': request.user.username,
#                                                           'origin_stations': origin_stations,
#                                                           'destination_stations': destination_stations})

# def payment_success(request):
#     # return render(request, 'buytickets/payment_success.html')
#     latest_ticket = Ticket.objects.filter(user=request.user).latest('id')

#     return render(request, 'buytickets/payment_success.html', {'latest_ticket': latest_ticket})




# from django.shortcuts import render
# from django.contrib.auth.decorators import login_required
# from .models import Ticket

# @login_required
# def ticket_details(request):
#     user_tickets = Ticket.objects.filter(user=request.user)
#     return render(request, 'buytickets/ticket_details.html', {'user_tickets': user_tickets})


















#Final working views


from django.shortcuts import render, redirect
from .forms import TicketForm
from .models import Ticket
from django.contrib.auth.decorators import login_required
from nextbus.models import Station,Bus
import uuid

@login_required
def buy_ticket(request):
    origin_stations = Station.objects.all()
    destination_stations = Station.objects.all()
    available_buses = Bus.objects.all() 

    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.ticket_number = uuid.uuid4().hex[:10]
            ticket.save()
            return redirect('buytickets:payment_success')

    else:
        form = TicketForm()
    return render(request, 'buytickets/buy_ticket.html', {'form': form, 'user_name': request.user.username,
                                                          'origin_stations': origin_stations,
                                                          'destination_stations': destination_stations,
                                                          'available_buses': available_buses})


# from django.shortcuts import render, redirect
# from .forms import TicketForm
# from .models import Ticket
# from django.contrib.auth.decorators import login_required
# from nextbus.models import Station, Bus
# import uuid
# import paypalrestsdk  # Import PayPal SDK
# from django.urls import reverse
# from django.conf import settings

# paypalrestsdk.configure({
#     "mode": "sandbox",  # Change to "live" for production
#     "client_id": settings.PAYPAL_CLIENT_ID,
#     "client_secret": settings.PAYPAL_SECRET,
# })

# @login_required
# def paypalbuy_ticket(request):
#     origin_stations = Station.objects.all()
#     destination_stations = Station.objects.all()
#     available_buses = Bus.objects.all() 

#     if request.method == 'POST':
#         form = TicketForm(request.POST)
#         if form.is_valid():
#             ticket = form.save(commit=False)
#             ticket.user = request.user
#             ticket.ticket_number = uuid.uuid4().hex[:10]
#             ticket.save()
#             # Retrieve the cost from the form data
#             cost = request.POST.get('cost')

#             # Create a PayPal payment object with the cost value
#             payment = paypalrestsdk.Payment({
#                 "intent": "sale",
#                 "payer": {
#                     "payment_method": "paypal",
#                 },
#                 "redirect_urls": {
#                     "return_url": request.build_absolute_uri(reverse('execute_payment')),
#                     "cancel_url": request.build_absolute_uri(reverse('payment_failed')),
#                 },
#                 "transactions": [
#                     {
#                         "amount": {
#                             "total": cost,  # Use the value from the form submission as the total amount
#                             "currency": "USD",
#                         },
#                         "description": "Payment for Ticket",
#                     }
#                 ],
#             })

#             # Create the PayPal payment
#             if payment.create():
#                 return redirect(payment.links[1].href)  # Redirect to PayPal for payment
#             else:
#                 return render(request, 'payment/payment_failed.html')
#     else:
#         form = TicketForm()
#     return render(request, 'buytickets/paypalbuy_ticket.html', {'form': form, 'user_name': request.user.username,
#                                                           'origin_stations': origin_stations,
#                                                           'destination_stations': destination_stations,
#                                                           'available_buses': available_buses})




from django.conf import settings




import paypalrestsdk
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import TicketForm
from .models import Ticket
from django.contrib.auth.decorators import login_required
from nextbus.models import Station, Bus
import uuid

# Configure PayPal SDK
paypalrestsdk.configure({
    "mode": "sandbox",  # Change to "live" for production
    "client_id": settings.PAYPAL_CLIENT_ID,
    "client_secret": settings.PAYPAL_SECRET,
})

@login_required
def paypalbuy_ticket(request):
    origin_stations = Station.objects.all()
    destination_stations = Station.objects.all()
    available_buses = Bus.objects.all() 

    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.ticket_number = uuid.uuid4().hex[:10]
            ticket.save()
            # Retrieve the cost from the form data
            cost = request.POST.get('cost')
            
            # Create a PayPal payment object
            payment = paypalrestsdk.Payment({
                "intent": "sale",
                "payer": {
                    "payment_method": "paypal",
                },
                "redirect_urls": {
                    "return_url": request.build_absolute_uri(reverse('execute_payment')),
                    "cancel_url": request.build_absolute_uri(reverse('payment_failed')),
                },
                "transactions": [
                    {
                        "amount": {
                            "total": cost,
                            "currency": "USD",
                        },
                        "description": "Payment for Bus Ticket",
                    }
                ],
            })

            # Create the PayPal payment
            if payment.create():
                return redirect(payment.links[1].href)  # Redirect to PayPal for payment
            else:
                return render(request, 'payment/payment_failed.html')

    else:
        form = TicketForm()
    return render(request, 'buytickets/paypalbuy_ticket.html', {'form': form, 'user_name': request.user.username,
                                                      'origin_stations': origin_stations,
                                                      'destination_stations': destination_stations,
                                                      'available_buses': available_buses})











def payment_success(request):
    # return render(request, 'buytickets/payment_success.html')
    latest_ticket = Ticket.objects.filter(user=request.user).latest('id')

    return render(request, 'buytickets/payment_success.html', {'latest_ticket': latest_ticket})







from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Ticket

@login_required
def ticket_details(request):
    user_tickets = Ticket.objects.filter(user=request.user)
    return render(request, 'buytickets/ticket_details.html', {'user_tickets': user_tickets})

Final NextTrip/NextTrip/buytickets/templates/buytickets/buy_ticket.html
{% extends 'loginpage/layout.html' %}
{% load static %}


{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buy Ticket</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .logo-img {
            display: flex;
            justify-content: center;
            align-items: flex-start;
        }

        .logo-img img {
            margin-top: 10px; /*Adjust as needed to position the image */
        }

        .form-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }

        .form-container:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

        .form-row {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .form-col {
            flex: 1;
            padding: 10px;
        }

        .form-label {
            font-size: 18px;
            font-weight: bold;
        }

        .form-input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 18px;
        }

        .form-select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 18px;
            appearance: none;
            background: url("data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/><path d='M0 0h24v24H0z' fill='none'/></svg>") no-repeat right 10px center;
        }

        .form-button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background: linear-gradient(to right, #f127e6, #f5af19);
            color: white;
            font-size: 18px;
            font-weight: bold;
            cursor: pointer;
        }

        .form-button:hover {
            opacity: 0.9;
        }

        .error {
            color: red;
            font-size: 16px;
            text-align: center;
        }
    </style>
</head>
<body>
    <a class="navbar-brand logo-img" href="#"><img src="{% static 'loginpage/Next Trip black.png' %}" alt="logo" width="100" height="100"></a>

    <h1 class="text-center mt-4">Buy Your Ticket</h1>
    <p class="text-center">Welcome, {{ user_name }}</p>
    <div class="form-container">
        {% if error %}
            <p class="error">{{ error }}</p>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-col">
                    <label for="bus" class="form-label">Bus Name:</label>
                    <select id="bus" name="bus" class="form-select">
                        <!-- Populate options dynamically from Django view -->
                        {% for bus in available_buses %}
                            <option value="{{ bus.id }}">{{ bus.number }} - {{ bus.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-col">
                    <label for="cost" class="form-label">Cost:</label>
                    <input type="number" id="cost" name="cost" class="form-input">
                </div>
            </div>
            <div class="form-row">
                <div class="form-col">
                    <label for="origin" class="form-label">Origin Station:</label>
                    <select id="origin" name="origin" class="form-select">
                        {% for station in origin_stations %}
                            <option value="{{ station.id }}">{{ station.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-col">
                    <label for="destination" class="form-label">Destination Station:</label>
                    <select id="destination" name="destination" class="form-select">
                        {% for station in destination_stations %}
                            <option value="{{ station.id }}">{{ station.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-col">
                    <label for="date" class="form-label">Date:</label>
                    <input type="date" id="date" name="date" value="{{ form.initial.date }}" class="form-input">
                </div>
                <div class="form-col">
                    <label for="time" class="form-label">Time:</label>
                    <input type="time" id="time" name="time" value="{{ form.initial.time }}" class="form-input">
                </div>
            </div>
            <button type="submit" class="form-button">Pay Now</button>
        </form>
    </div>
</body>
</html>
{% endblock %}

Final NextTrip/NextTrip/buytickets/templates/buytickets/payment_success.html
{% extends 'loginpage/layout.html' %}
{% load static %}


{% block body %}
<!DOCTYPE html>
<html>
<head>
    <title>Your Most Recent Ticket Details</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .logo-img {
    display: flex;
    justify-content: center;
    align-items: flex-start; /
    }

    .logo-img img {
     margin-top: 10px; /*Adjust as needed to position the image */
     margin-bottom: -50px;
    }
        .card {
            margin: 20px;
            padding: 20px;
            border-radius: 10px;
            background-color: #f8f9fa;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

        .card-title {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
        }

        .card-text {
            font-size: 18px;
            color: #343a40;
        }

        .verified {
            color: #28a745;
            font-weight: bold;
        }

        .not-verified {
            color: #dc3545;
            font-weight: bold;
        }
        .review{
            margin-bottom: -20px;
        }
        p{
            font-weight: bold;
        }

        a {
      /* font-size: 24px; */
      font-family: Arial, sans-serif;
      animation: changeColor 1s infinite; /* Use CSS animation to continuously change color */
    }

    /* Keyframes for changing color */
    @keyframes changeColor {
      0% { color: red; } /* Start with red */
      50% { color: blue; } /* Change to blue at halfway */
      100% { color: green; } /* Change to green at end */
    }
    </style>
</head>
<body>
    <a class="navbar-brand logo-img" href="#"><img src="{% static 'loginpage/Next Trip black.png' %}" alt="logo" width="100" height="100" ></a>

    <h1 class="text-center mt-4">Your Most Recent Ticket Details</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">User: {{ latest_ticket.user }}</h5>
                        <p class="card-text">Ticket ID: {{ latest_ticket.id }}</p> <!-- Display ticket ID here -->
                        <p class="card-text">Bus: {{ latest_ticket.bus.name }}</p> <!-- Display bus name here -->
                        <p class="card-text">Bus reg_number: {{ latest_ticket.bus.reg_number }}</p> 
                
                        <p class="card-text">Origin: {{ latest_ticket.origin }}</p>
                        <p class="card-text">Destination: {{ latest_ticket.destination }}</p>
                        <p class="card-text">Date: {{ latest_ticket.date }}</p>
                        <p class="card-text">Time: {{ latest_ticket.time }}</p>
                        <p class="card-text">Ticket Number: {{ latest_ticket.ticket_number }}</p>
                
                        {% if latest_ticket.is_verified %}
                            <p class="card-text verified">Verified</p>
                        {% else %}
                            <p>Your ticket is awaiting verification by a manager.</p>
                            <p class="card-text not-verified">Not Verified</p>
                        {% endif %}
                        <p class="review changingColor" id="changingColor"><a href="{% url 'reviews:review_form' %}"> review your journey</a></p>
                        <!-- Add more fields as needed -->
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
</body>
</html>

{% endblock %}

Final NextTrip/NextTrip/buytickets/templates/buytickets/paypalbuy_ticket.html
{% extends 'loginpage/layout.html' %}
{% load static %}


{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buy Ticket</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .logo-img {
    display: flex;
    justify-content: center;
    align-items: flex-start; /
    }

    .logo-img img {
     margin-top: 10px; /*Adjust as needed to position the image */
    }
        .form-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }

        .form-container:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

        .form-row {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .form-col {
            flex: 1;
            padding: 10px;
        }

        .form-label {
            font-size: 18px;
            font-weight: bold;
        }

        .form-input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 18px;
        }

        .form-select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 18px;
            appearance: none;
            background: url("data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/><path d='M0 0h24v24H0z' fill='none'/></svg>") no-repeat right 10px center;
        }

        .form-button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background: linear-gradient(to right, #f127e6, #f5af19);
            color: white;
            font-size: 18px;
            font-weight: bold;
            cursor: pointer;
        }

        .form-button:hover {
            opacity: 0.9;
        }

        .error {
            color: red;
            font-size: 16px;
            text-align: center;
        }
    </style>
    <body>
        <a class="navbar-brand logo-img" href="#"><img src="{% static 'loginpage/Next Trip black.png' %}" alt="logo" width="100" height="100"></a>
    
        <h1 class="text-center mt-4">Buy Your Ticket</h1>
        <p class="text-center">Welcome, {{ user_name }}</p>
        <div class="form-container">
            {% if error %}
                <p class="error">{{ error }}</p>
            {% endif %}
            <form action="{% url 'buytickets:paypalbuy_ticket' %}" method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-col">
                        <label for="bus" class="form-label">Bus Name:</label>
                        <select id="bus" name="bus" class="form-select">
                            {% for bus in available_buses %}
                                <option value="{{ bus.id }}">{{ bus.number }} - {{ bus.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-col">
                        <label for="cost" class="form-label">Cost:</label>
                        <input type="number" id="cost" name="cost" class="form-input">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-col">
                        <label for="origin" class="form-label">Origin Station:</label>
                        <select id="origin" name="origin" class="form-select">
                            {% for station in origin_stations %}
                                <option value="{{ station.id }}">{{ station.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-col">
                        <label for="destination" class="form-label">Destination Station:</label>
                        <select id="destination" name="destination" class="form-select">
                            {% for station in destination_stations %}
                                <option value="{{ station.id }}">{{ station.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-col">
                        <label for="date" class="form-label">Date:</label>
                        <input type="date" id="date" name="date" value="{{ form.initial.date }}" class="form-input">
                    </div>
                    <div class="form-col">
                        <label for="time" class="form-label">Time:</label>
                        <input type="time" id="time" name="time" value="{{ form.initial.time }}" class="form-input">
                    </div>
                </div>
                <button type="submit" class="form-button">Pay Now</button>
            </form>
        </div>
    </body>
    </html>

    {% endblock%}