Final NextTrip/NextTrip/NextTrip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('loginpage.urls')),
    path('nextbus/',include('nextbus.urls')),
    path('buytickets/',include('buytickets.urls')),
    #  path('buytickets/', include('buytickets.urls',namespace='buytickets')),
    path('reviews/',include('reviews.urls')),
    # path('payment/',include('payment.urls')),


     

]

Final NextTrip/NextTrip/buytickets/urls.py
from django.urls import path
from . import views 
from .views import ticket_details

app_name = 'buytickets'

urlpatterns = [
    path('buy_ticket/', views.buy_ticket, name='buy_ticket'),
    path('paypalbuy_ticket/', views.paypalbuy_ticket, name='paypalbuy_ticket'),

      path('paypalbuy_ticket/', views.paypalbuy_ticket, name='paypalbuy_ticket'),

    path('payment_success/', views.payment_success, name='payment_success'),
    # path('verify_ticket/<int:ticket_id>/', views.verify_ticket, name='verify_ticket'),
    # path('manager/', views.manager_view, name='manager_view'),
    # Other URL patterns
    path('ticket-details/', ticket_details, name='ticket_details'),
]

Final NextTrip/NextTrip/loginpage/urls.py
# urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

# Django admin header customization
admin.site.site_header= "NextTrip Dashboard"
admin.site.site_title = "Welcome to NextTrip Dashboard"
admin.site.index_title="Welcome to NextTrip"


urlpatterns = [
    path('signup/',views.SignupPage,name='signup'),
    path('',views.LoginPage,name='login'),
    path('home/',views.HomePage,name='home'),
    path('logout/',views.LogoutPage,name='logout'),
]

Final NextTrip/NextTrip/nextbus/urls.py
from django.urls import path
from nextbus import views

urlpatterns = [
    path('search/', views.search_buses, name='search_buses'),
    path('bus/<str:bus_name>/', views.bus_reviews, name='bus_reviews'),
    
    #  path('get_stations/', views.get_stations, name='get_stations'),


    # path('get_station_suggestions/', views.get_station_suggestions, name='get_station_suggestions'),

    


]

Final NextTrip/NextTrip/loginpage/models.py
from django.db import models

# Create your models here.

Final NextTrip/NextTrip/loginpage/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='login')  #used decorators library to overcome the direct access of the Home page without login in after applying decorator we can not directly go into home page with search bar it require login information
def HomePage(request):
    return render(request, 'loginpage/home.html')
#return HttpResponse("This is the home page")

def SignupPage(request):
    if request.method=='POST':
        uname=request.POST.get('username')
        email=request.POST.get('email')
        pass1=request.POST.get('password1')
        pass2=request.POST.get('password2')
        print(uname,email,pass1,pass2)

        if User.objects.filter(username=uname).exists():
            return HttpResponse("Username already exists. Please choose a different username.")

        # Check if passwords match
        if pass1 != pass2:  #checks constraints it create the database only if it meet requirement else it will not create the database
            return HttpResponse("Passwords do not match. Please try again.")
        else:
            # Create a new user
            my_user = User.objects.create_user(uname, email, pass1)
            my_user.save()
            # return HttpResponse("Login succesfull")
            return redirect('login')  #redirect into login page

    return render(request,'loginpage/signup.html')


def LoginPage(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        pass1=request.POST.get('pass')
        user=authenticate(request,username=username,password=pass1)
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            return HttpResponse("Username or Password is incorrect")


    return render(request,'loginpage/login.html')
    

def search_buses(request):
    return render(request, 'nextbus/search_form.html')




def LogoutPage(request):
    logout(request)
    return redirect('login')



def HomePage(request):
    username = request.user.username  # Access the username
    return render(request, 'loginpage/home.html', {'username': username})

def search_buses(request):
    username = request.user.username
    return render(request, 'nextbus/search_form.html', {'username': username})

Final NextTrip/NextTrip/loginpage/templates/loginpage/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <!-- Include Remixicons CSS for icons -->
   <link href="https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css" rel="stylesheet">

   <!-- Include your custom CSS file -->
   <link rel="stylesheet" href="{% static 'loginpage/styles.css' %}">

   <title>Next Trip</title>
</head>
<body>
   <!-- HEADER -->
   <header class="header">
      <nav class="nav container">
         <div class="nav__data">
            <a href="#" class="nav__logo">
               <!-- <i class="ri-planet-line"></i> -->
               <i class="ri-bus-fill"></i> NextTrip
            </a>
            
            <!-- Nav toggle button for mobile -->
            <div class="nav__toggle" id="nav-toggle">
               <i class="ri-menu-line nav__burger"></i>
               <i class="ri-close-line nav__close"></i>
            </div>
         </div>

         <!-- NAV MENU -->
         <div class="nav__menu" id="nav-menu">
            <ul class="nav__list">
               <li><a href="{% url 'home' %}" class="nav__link">Home</a></li>

               <li><a href="{% url 'search_buses' %}" class="nav__link">Search Bus</a></li>

               <!-- DROPDOWN 1 -->
               <li class="dropdown__item">
                  <div class="nav__link">
                     Ticket Booking <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                  </div>

                  <ul class="dropdown__menu">
                     <li>
                        <a href="{% url 'buytickets:buy_ticket' %}" class="dropdown__link">
                           <i class="ri-pie-chart-line"></i> Buy Ticket
                        </a>                          
                     </li>

                     <li>
                        <a href="{% url 'buytickets:paypalbuy_ticket' %}" class="dropdown__link">
                           <i class="ri-arrow-up-down-line"></i> UPI payment
                        </a>
                     </li>

                     <!-- DROPDOWN SUBMENU -->
                     <li class="dropdown__subitem">
                        <div class="dropdown__link">
                           <i class="ri-bar-chart-line"></i> Ticket Details <i class="ri-add-line dropdown__add"></i>
                        </div>

                        <ul class="dropdown__submenu">
                           <li>
                              <a  href="{% url 'buytickets:ticket_details' %}" class="dropdown__sublink">
                                 <i class="ri-file-list-line"></i> Ticket History
                              </a>
                           </li>

                           <li>
                              <a href="{% url 'buytickets:ticket_details' %}" class="dropdown__sublink">
                                 <i class="ri-cash-line"></i> Payments
                              </a>
                           </li>

                           <li>
                              <a href="#" class="dropdown__sublink">
                                 <i class="ri-refund-2-line"></i> Refunds
                              </a>
                           </li>
                        </ul>
                     </li>
                  </ul>
               </li>
               
               <li><a href="{% url 'buytickets:ticket_details' %}" class="nav__link">Ticket History</a></li>

               <!-- DROPDOWN 2 -->
               <li class="dropdown__item">
                  <div class="nav__link">
                     Users <i class="ri-arrow-down-s-line dropdown__arrow"></i>
                  </div>

                  <ul class="dropdown__menu">
                     <li>
                        <a href="{% url 'logout' %}" class="dropdown__link">
                           <i class="ri-user-line"></i> Logout
                        </a>                          
                     </li>

                     <li>
                        <a href="{% url 'admin:index' %}" class="dropdown__link">
                           <i class="ri-lock-line"></i> Admin Login
                        </a>
                     </li>

                     <li>
                        <a href="#" class="dropdown__link">
                           <i class="ri-message-3-line"></i> Query
                        </a>
                     </li>
                  </ul>
               </li>

               <li><a href="#" class="nav__link">Contact</a></li>
            </ul>
         </div>
      </nav>
   </header>

   <!-- BODY CONTENT -->
   {% block body %}

   {% endblock %}

   <!-- Include your custom JavaScript file -->
   <script src="{% static 'loginpage/script.js' %}"></script>
</body>
</html>

Final NextTrip/NextTrip/loginpage/templates/loginpage/login.html
<!-- 
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login Page</title>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

button{
    margin-bottom: 0.9rem;
}
    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        <h3>Login Here</h3>
        {% csrf_token %} 
        <label for="username">Username</label>
        <input type="text" placeholder="Enter Username" id="username" name="username">

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password" name="pass">

        <button type="submit">Log In</button>
        


        <a href="{% url 'signup' %}" >Create a account</a>

    </form>
</body>
</html> -->

























<!-- *********************** -->
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- <link rel="shortcut icon" type="image/png" href="NT.png" /> -->
    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body{
            background: linear-gradient(to bottom, #2B0087, rgba(49, 11, 21, 0.555)), url('https://t4.ftcdn.net/jpg/02/74/33/85/360_F_274338583_CuXr9eaYrzH8B0AvGywzEAyWZ2fFopzq.jpg');
            
            color: rgb(255, 255, 255);
             /* background: url(https://t4.ftcdn.net/jpg/02/74/33/85/360_F_274338583_CuXr9eaYrzH8B0AvGywzEAyWZ2fFopzq.jpg); */
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            background-attachment: fixed;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container{
            background-color: transparent;
            backdrop-filter: blur(10px);
            width: 600px;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.6);
            border: 1px solid rgba(214, 209, 209, 0.685);
        }
        .container form{
            display: grid;
            justify-content: center;
            flex-direction: column;
            width: 100%;
            
        }
        label{
            font-size: 17px; font-weight: bold;
        }
        input{
            height: 38px;outline: none;border: 0;
            padding: 10px; border-radius: 8px;
        }
        button{
            background-color: rgb(35, 184, 35);color: rgb(255, 255, 255);border: 0;outline: none;
            height: 50px;border-radius: 10px;
        }
        a{
            color: rgb(189, 189, 197);
        }
        .form-text{
            color: rgb(230, 230, 230);
        }
        span{
            width: 50%;
            text-align: center;
        }
        form input[type="checkbox"]{
            height: 15px;
            font-size: 10px;
            width: 10% !important;
            text-align: left;
        }
        @media only screen and (max-width: 767px) {
  /* Styles for mobile devices go here */
            body {
                    background: linear-gradient(to bottom, #141fb4, rgba(49, 11, 21, 0.555)), url('https://t4.ftcdn.net/jpg/02/74/33/85/360_F_274338583_CuXr9eaYrzH8B0AvGywzEAyWZ2fFopzq.jpg');
                }
    </style>
</head>
<body><center>
    <div class="container">
        <img src="{% static 'loginpage/Next Trip white.png' %}"  width="150" height="150" alt="Logo">
        <div class="form">
            <h2>Login Form</h2>
            <form method="post">
        
        {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Email address</label>
                  <input type="text" class="form-control" id="username" name="username" aria-describedby="emailHelp">
                  <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3">
                  <label for="passwords" class="form-label">Password</label>
                  <input type="password" class="form-control" name="pass" id="passwords">
                        
                </div>
                <button type="submit" class="btn btn-primary" >Log in</button>
                <p>Don't have an account? </p>
        <a href="{% url 'signup' %}" >Create an account</a>

              </form>
        </div>
    </div>
    </center>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


</body>
</html>

Final NextTrip/NextTrip/loginpage/templates/loginpage/safehome.html
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>


    <ul class="nav nav-pills justify-content-end p-1 me-5 mt-2">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
        <ul class="dropdown-menu">
    
    <li></li>
<a href="{% url 'search_buses' %}" class="btn btn-primary">NextBus</a>
<li></li>
          <li><a class="dropdown-item" href="{% url 'buytickets:buy_ticket' %}">Buy Ticket</a></li>
          <li><hr class="dropdown-divider"></li>
          <!-- <li><a class="dropdown-item" href="#">verify Ticket</a></li>
          <li><hr class="dropdown-divider"></li> -->
          <li><a class="dropdown-item" href="#">Ticket History</a></li>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">LogOut</a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
      </li> -->
    </ul>


    <h2>Welcome, {{ username }}!</h2>

Final NextTrip/NextTrip/loginpage/templates/loginpage/signup.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <title>Signup Page</title>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 600px;
    width: 450px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 40px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 2px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 14px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

button{
    margin-bottom: 0.9rem;
}
a{
    margin-top: 2rem;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="" method="post">
        {% csrf_token %} 
        <h3>Signup Here</h3>

        <label for="username">Username</label>
        <input type="text" placeholder="Username" name="username" id="username">

        <label for="email">Email</label>
        <input type="email" placeholder="Email or Phone" name="email" id="email">

        <label for="password1">Password</label>
        <input type="password" placeholder="Password" id="password1" name="password1">


        <label for="password2">Confrom Password</label>
        <input type="password" placeholder="Confrom Password" id="password2" name="password2">
        <button type="submit">Signup</button>
        
        <a href="{% url 'login' %}">i have already account</a>
        <br>

    </form>
</body>
</html> -->










<!-- ************* -->









{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="./NT.png" />
    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body{
           
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
            margin: 0;
            background:linear-gradient(to bottom, #2B0087, rgba(49, 11, 21, 0.555)),url(https://t4.ftcdn.net/jpg/02/74/33/85/360_F_274338583_CuXr9eaYrzH8B0AvGywzEAyWZ2fFopzq.jpg);
            background-repeat: no-repeat;
            background-position: center;
            background-attachment: fixed;
            background-size: cover;
            width: 100%;
        }
        .container{
            background-color: transparent;
            backdrop-filter: blur(10px);
            width: 600px;
            /* padding: 10px; */
            border-radius: 8px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.6);
            border: 1px solid rgba(214, 209, 209, 0.685);
        }
        .container form{
            display: grid;
            justify-content: center;
            flex-direction: column;
            width: 100%;
        }
        label{
            font-size: 17px; font-weight: 600;
        }
        input{
            height: 38px;outline: none;border: 0;
            padding: 10px; border-radius: 8px; width: 400px;
        }
        button{
            background-color: rgb(35, 184, 35);color: rgb(255, 255, 255);border: 0;outline: none;
            height: 50px;border-radius: 10px; margin-top: 10px;
        }
        img{
            display: flex;justify-content: center;
        }
        h2{
            text-align: center;
            font-size: 30px;color: rgb(255, 255, 255);
        }
        .form-text{
            color: rgb(231, 225, 225);
        }
        span{
            width: 50%;
            text-align: center;
        }
        form input[type="checkbox"]{
            height: 15px;
            font-size: 10px;
            width: 10% !important;
            text-align: left;
        }
    </style>
</head>
<body>
    <div class="container">
        <center><img src="{% static 'loginpage/Next Trip white.png' %}" width="150" height="150" alt=""></center>
        <div class="form">
            <h2>Register</h2>
            <form action="" method="post">
                {% csrf_token %} 
                <h3>Signup Here</h3>
                

                  <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label" 
                    >Name</label>
                    <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" >
                    
                  </div>
                  <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="email" class="form-control" name="email" id="exampleInputEmail2" aria-describedby="emailHelp" >
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                  </div>
                
                

                  <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password1" id="exampleInputPassword1">
                    <span>Show Password<input type="checkbox" onclick="showPass()" id="showPasswordButton"></span>
                  </div>
                  <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
                    <input type="password" class="form-control" name="password2" id="exampleInputConfirmPassword">
                  </div>
                    
                    <button type="submit" class="btn btn-primary" >Signup</button>

        <a href="{% url 'login' %}">i have already account</a>
                    
            </form> 
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>

function showPass() {
  const passwordInput = document.getElementById('exampleInputPassword1');
  const showPasswordButton = document.getElementById('showPasswordButton');

  if (showPasswordButton.checked) {
    passwordInput.type = 'text';
    showPasswordButton.textContent = 'Hide password';
  } else {
    passwordInput.type = 'password';
    showPasswordButton.textContent = 'Show password';
  }
}
        </script>
</body>
</html>